---
- name: Install PostgreSQL
  package:
    name:
      - postgresql
      - python3-psycopg2
    state: present

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create SonarQube database
  community.postgresql.postgresql_db:
    name: "{{ sonarqube_db_name }}"
    encoding: UTF-8
  become: true
  become_user: postgres

- name: Grant database privileges to SonarQube user
  community.postgresql.postgresql_privs:
    db: "{{ sonarqube_db_name }}"
    privs: ALL
    type: database
    role: "{{ sonarqube_db_user }}"
  become: true
  become_user: postgres

- name: Grant schema and objects privileges to SonarQube user
  community.postgresql.postgresql_privs:
    db: "{{ sonarqube_db_name }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ sonarqube_db_user }}"
    grant_option: true
  become: true
  become_user: postgres

- name: Set default privileges for SonarQube user
  community.postgresql.postgresql_privs:
    db: "{{ sonarqube_db_name }}"
    type: default_privs
    privs: ALL
    objs: ALL_DEFAULT
    role: "{{ sonarqube_db_user }}"
    grant_option: true
  become: true
  become_user: postgres
