---
- name: Download SonarQube
  get_url:
    url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
    dest: "/var/lib/sonarqube-{{ sonarqube_version }}.zip"
    mode: "0644"

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Extract SonarQube
  unarchive:
    src: "/var/lib/sonarqube-{{ sonarqube_version }}.zip"
    dest: /opt
    remote_src: true
    creates: "/opt/sonarqube-{{ sonarqube_version }}"
